spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/TrainingDB
        username: postgres
        password: 123456

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

json:
    file:
        path: C:/Users/hoang/Downloads/demoGradle/demo/src/main/resources/InsuranceType.json



